def f2(a):
    c = 10
    print(a+x+c)

x = 4

f2(3)
print(x)
print(c) # VAI DAR UM ERRO POIS A VARIÁVEL 'c' FOI CRIADA DENTRO DA FUNÇÃO 'f2' #